variables:
  DOCKER_REGISTRY: "docker.grammatech.com"
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_PATH
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/. /root/quicklisp/local-projects/$CI_PROJECT_NAME

.test-template: &test
  stage: test
  script:
    - LISP=$LISP make check
  except:
    - schedules

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

dependents:
  stage: deploy
  inherit:
    default: false
  script:
    - "curl -X POST -F token=064aa88b0cae92c6b22885598f3ccf -F ref=$CI_BUILD_REF_NAME https://git.grammatech.com/api/v4/projects/1312/trigger/pipeline" # gt
  only:
    - master
  except:
    - schedules

build-nightly:
  stage: build
  inherit:
    default: false
  script:
    - docker build --no-cache -t $DOCKER_REGISTRY/$CI_PROJECT_PATH .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH
  only:
    - schedules
