variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_PATH
  tags: ["kubernetes", "cluster"]
  before_script:
    - cp -r $(pwd)/ /root/quicklisp/local-projects/

.test-template: &test
  stage: test
  script:
    - LISP=$LISP make real-check
  except:
    - schedules

test-sbcl:
  variables:
    LISP: 'sbcl'
  <<: *test

test-ccl:
  variables:
    LISP: 'ccl'
  <<: *test

readme:
  stage: test
  script:
    - make check-readme
  except:
    - schedules

dependent-gt:
  stage: deploy
  only: [master]
  except: [schedules]
  trigger: synthesis/gt

scheduled-build:
  stage: build
  inherit:
    default: false
  script:
    - docker build --no-cache -t $DOCKER_REGISTRY/$CI_PROJECT_PATH .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH
  only:
    - schedules
